# Generated by Django 5.0.6 on 2024-08-31 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_category_property_city_property_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
