# Generated by Django 5.0.6 on 2024-09-04 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_remove_category_description_category_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='super_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.category'),
        ),
    ]
