# Generated by Django 5.0.6 on 2024-09-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_alter_category_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16, null=True),
        ),
    ]
