# Generated by Django 5.1.1 on 2024-10-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_likerelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
